MONGO_CONNECTION_URI = "mongodb://root:root@mongodb:27017/genlicense"

MYSQL_CONNECTION_HOST = "mysqldb"
MYSQL_CONNECTION_PORT = 3306
MYSQL_CONNECTION_USER = "root"
MYSQL_CONNECTION_PASSWORD = "root"
MYSQL_CONNECTION_DATABASE = "ctasia"